language: node_js
node_js:
  - node
script:
  - npm test
  - npm run build
deploy:
  provider: s3
  access_key_id: 
  secret_access_key: AKIAXIIWEG4XVIWC64OF
    secure: cwkiY3vU+ykOgtcJLaFWok618olhtBgZuCTWRPGUGcropyW/Nr0h/DGPt9/0bbCqMVDh4tnBT9kjztLityc2pYn5ZOb4xqa9oETRnGxWFZPEkzZlCwOYgiVe2LozUvG17Fnhe6fipf4SRPO4FbF7eSW9QzL+McsvG3Qx9gbef8l8eoVsrBnfty+yYzwtC4agozy4oCw6LFI82J9hEWuhLFNqY6ZBCImn7s2J+NWNll3KzZo71fqfmdcYZ5EiC41RQcQU4OLhVUgpuW9r4dpgz8tqEXTsHJnLvqzlu05MXvQFgTrFTmV8lUth69xQj+WxQZV1VNcKC2C8el1EOMDo6OMQY4j6574HUHQoIdUwFtP95HEW5XyNs4LoN2rg6FED+bNSFZGZ+0tnkRqsNlcB9nv+VcrzPzzqY+XQLhjVRBTGr7OSbeafwrSyUr0W8cIrTxVJ7SmIx4oME57UYfvJc3rpEwXq690Yp9nFOvbfJcvUa5XheAryQIOJUCtVMNLPkKxhIbutlqeWWeXvgxc1JxLBQ3Qy6X299OXvXtrtu8MFVhWLxHRLcC4nOl63QepgolvJ+wVEldNQwu3EoFUdOnOb313cys8OO5qngNG+GSkxUKpI8AGQWkQnaIfJmIV5ARXBQRSIhAcdTJDtteZXqqnm/wF7RgqM1mrT7bu8P/U= 
  bucket: devops-travisci-bucket
  acl: bucket_owner_full_control
  region: us-west-2
  on:
    repo: glanzmichael25/my-app
  local_dir: build
